
CREATE TABLE IF NOT EXISTS `#__servicos_services` (
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `asset_id` int(10) unsigned NOT NULL DEFAULT 0,
    `title` varchar(255) NOT NULL DEFAULT '',
    `alias` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    `introtext` mediumtext NOT NULL COMMENT 'O que é?',
    `target_audience` mediumtext NOT NULL COMMENT 'Quem pode utilizar?',
    `steps` mediumtext NOT NULL COMMENT 'Etapas',
    `other_info` mediumtext NOT NULL COMMENT 'Outras Info',
    `state` tinyint(3) NOT NULL DEFAULT 0,
    `catid` int(10) unsigned NOT NULL DEFAULT 0,
    `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `created_by` int(10) unsigned NOT NULL DEFAULT 0,
    `modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `modified_by` int(10) unsigned NOT NULL DEFAULT 0,
    `checked_out` int(10) unsigned NOT NULL DEFAULT 0,
    `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `access` int(10) unsigned NOT NULL DEFAULT 0,
    `hits` int(10) unsigned NOT NULL DEFAULT 0,
    `featured` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `ordering` int(11) NOT NULL DEFAULT 0,
    `language` char(7) NOT NULL DEFAULT '*',
    `params` text,
    PRIMARY KEY (`id`),
    KEY `idx_access` (`access`),
    KEY `idx_checkout` (`checked_out`),
    KEY `idx_state` (`state`),
    KEY `idx_catid` (`catid`),
    KEY `idx_featured_catid` (`featured`,`catid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
